-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Gegenereerd op: 28 sep 2018 om 10:18
-- Serverversie: 10.1.29-MariaDB
-- PHP-versie: 7.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `gameplayparty`
--

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `bioscopen`
--

CREATE TABLE `bioscopen` (
  `bios_id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `image` varchar(50) NOT NULL,
  `begintijd` varchar(50) NOT NULL,
  `eindtijd` varchar(50) NOT NULL,
  `bios_naam` varchar(50) NOT NULL,
  `adres` varchar(50) NOT NULL,
  `postcode` varchar(50) NOT NULL,
  `stad` varchar(50) NOT NULL,
  `provincie` varchar(50) NOT NULL,
  `bereikbaar_auto` text NOT NULL,
  `bereikbaar_ov` text NOT NULL,
  `bereikbaar_fiets` text NOT NULL,
  `rolstoeltoegankelijkheid` enum('0','1') NOT NULL DEFAULT '0',
  `voorwaarden` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Gegevens worden geëxporteerd voor tabel `bioscopen`
--

INSERT INTO `bioscopen` ( `bios_naam`, `image`, `adres`, `postcode`, `stad`, `provincie`, `begintijd`, `eindtijd`, `bereikbaar_auto`, `bereikbaar_ov`, `bereikbaar_fiets`, `rolstoeltoegankelijkheid`, `voorwaarden`) VALUES
( 'Kinepolis Almere', 'almere.jpg', 'Forum 16', '1315 TH', 'Almere', 'Flevoland', '2018-10-16 16:00:00', '2018-10-16 20:00:00', 'Met de auto bereikt u Kinepolis Almere door richting Centrum te volgen. Rondom Kinepolis Almere is volop parkeergelegenheid. De P6 Hospitaalgarage of P7 Schippersgarage zijn het gunstigst gelegen t.o.v. de bioscoop. Parkeert u na 18:00 uur, dan geldt het maximale avondtarief van â‚¬5,25 voor de hele avond. ', 'U kunt ons met de trein en bus zeer makkelijk bereiken. Vanaf station Almere Centrum loopt u in circa 5 minuten in zuidelijke richting richting naar Almere Citymall. Kinepolis Almere is tevens goed bereikbaar per bus via haltes Passage (buslijn M1 & M4) en Flevoziekenhuis (buslijn M5 en M7). Voor actuele bustijden kijkt u op 9292.nl.', 'Citymall Almere heeft diverse (bewaakte) fietsenstallingen, bijvoorbeeld aan de Hospitaaldreef.', '1', 'N.B. Bovenstaande prijzen zijn per persoon, zijn niet geldig bij evenementen, speciale voorstellingen of besloten voorstellingen en altijd exclusief toeslagen.\r\nKinderen t/m 2 jaar hebben gratis toegang, wanneer ze bij een betalende volwassene op schoot zitten. Is dat niet wenselijk, dan dient er een ticket gekocht te worden.\r\nZondagochtend voordeel geldt alleen op zondag voor de voorstellingen tot 11:59 uur.\r\nOp vertoon van een geldige CJP/Cultuurkaart of BankGiro Loterij VIP-KAART aan de kassa van de bioscoop ontvang je korting. Let op: deze korting is alleen geldig van maandag t/m vrijdagmiddag maar niet gedurende vakanties (met uitzondering van de zomervakantie). Deze korting is per persoon en niet geldig in combinatie met andere kortingsacties, evenementen, speciale voorstellingen of besloten voorstellingen.\r\nVoor de voorwaarden van het familieticket, het 5-sterrenticket en de 10-sterrenticket zie FAQ.'),
( 'Kinepolis Breda', 'breda.jpg', 'Bavelseparklaan 4', '4817 ZX ', 'Breda', 'Noord-Brabant', '2018-10-16 12:00:00', '2018-10-16 15:00:00', 'Met de auto kunt u de bioscoop makkelijk bereiken. LET OP: stel uw navigatiesysteem in op het adres Minervum, Breda. Zodra u vanuit Breda-centrum de A27 kruist of vanaf de snelweg afslag 15-Breda hebt genomen, zet u uw navigatie uit en volgt u de gele bordjes richting Breepark. Houd de borden richting Mc Donalds aan en neem op de rotonde de rechterbaan. De bioscoop bevindt zich aan uw rechterzijde. De parkeergarage zit onder de bioscoop. U kunt bij Kinepolis Breda GRATIS parkeren!', 'U kunt Kinepolis Breda vanaf 11 december goed bereiken met het openbaar vervoer. Maandag t/m vrijdag (tot 18:00 uur) stopt buslijn 131 vanaf het Centraal Station Breda (richting Tilburg) bij de bushalte bij Breepark. s Avonds en in het weekend rijden buslijnen 325, 326 en 327 tussen het Centraal Station Breda en Breepark. De bushalte op Breepark bevindt zich direct naast de bioscoop.', 'De gratis en overdekte parkeergarage heeft tevens een zeer grote fietsenstalling.', '1', 'N.B. Bovenstaande prijzen zijn per persoon, zijn niet geldig bij evenementen, speciale voorstellingen of besloten voorstellingen en altijd exclusief toeslagen.\r\nKinderen t/m 2 jaar hebben gratis toegang, wanneer ze bij een betalende volwassene op schoot zitten. Is dat niet wenselijk, dan dient er een ticket gekocht te worden.\r\nBij een kinderkaartje of jeugdkaartje kan naar het identiteitsbewijs van het kind/jongere gevraagd worden om de leeftijd vast te stellen. U dient deze dan te tonen om toegang te verkrijgen.\r\nOchtendvoorstellingen zijn enkel op weekenddagen, feestdagen en in vakanties tot 12:00 uur.\r\nOp vertoon van een geldige CJP/Cultuurkaart. BankGiro Loterij VIP-KAART of studentenkaart aan de kassa van de bioscoop ontvang je korting. Let op: deze korting is alleen geldig van maandag t/m vrijdagmiddag maar niet gedurende vakanties (met uitzondering van de zomervakantie). Deze korting is per persoon en niet geldig in combinatie met andere kortingsacties, evenementen, speciale voorstellingen of besloten voorstellingen.\r\nVoor de voorwaarden van het familieticket, het 5-sterrenticket en de 10-sterrenticket zie FAQ.'),
('Kinepolis CineMagnus Schagen', 'cinemagnus.jpg', 'Grotewallerweg 2', '1742 NM', 'Schagen', 'Noord-Holland', '2018-10-16 12:00:00', '2018-10-16 16:00:00', 'Vanuit alle richtingen volgt u de ANWB borden richting Witte Paal, de bioscoop bevindt zich aan het begin van het bedrijventerrein. De ingang naar het parkeerterrein van de bioscoop zit aan de Grotewallerweg. Voor wie met de auto wil komen; CineMagnus beschikt over eigen (gratis) parkeerplaatsen. Mochten deze vol zijn, dan kunt u uw auto parkeren op de gratis parkeerplaatsen van onze overburen, de Gamma.', 'Het NS- station is op 3 minuten lopen van de bioscoop en de bus stopt voor de deur.', 'CineMagnus is goed bereikbaar per fiets. Volg hiervoor de borden Witte Paal. Voor de bioscoop zijn fietsenrekken aanwezig.', '1', 'N.B. Bovenstaande prijzen zijn per persoon, zijn niet geldig bij evenementen, speciale voorstellingen of besloten voorstellingen en altijd exclusief toeslagen en aanschaf 3D bril.\r\nVroege Vogel Voorstellingen gelden alleen (aanvang voor 12.00 uur) in het weekend en tijdens de schoolvakanties. De voorstelling is niet mogelijk in combinatie met andere kortingen en acties.\r\nVoor de bovengenoemde \"Speciale voorstellingen\" zijn kortingen en acties niet mogelijk.\r\nOp vertoon van een geldige CJP-Cultuurkaart, BankGiroLoterij VIP-kaart of studentenkaart aan de kassa van de bioscoop ontvang je korting. Let op: deze korting is alleen geldig van maandag t/m vrijdagmiddag maar niet gedurende vakanties (met uitzondering van de zomervakantie). Deze korting is per persoon en niet geldig in combinatie met andere kortingsacties, evenementen, speciale voorstellingen of besloten voorstellingen.\r\nFamilietickets zijn alleen geldig voor vier personen waarvan minimaal twee kinderen jonger dan 12 jaar en minimaal Ã©Ã©n volwassene. Alleen geldig bij kindervoorstellingen in de middag wanneer alle vier de personen naar dezelfde filmvoorstelling gaan. '),
('Kinepolis CineMeerse Hoofddorp', 'cinemeerse.jpg', 'Raadhuisplein 12', '2132 TZ ', 'Hoofddorp', 'Noord-Holland', '2018-10-16 12:00:00', '2018-10-16 18:00:00', 'Met de auto bereikt u CineMeerse door de borden richting Centrum te volgen. Rondom CineMeerse is volop parkeergelegenheid. U kunt uw auto bij Q-Park Polderplein in Hoofddorp parkeren en aan de kassa van CineMeerse een waardekaart kopen. Met deze waardekaart kunt u 3 uur parkeren voor maar â‚¬ 1,50*!', '-', 'CineMeerse is goed bereikbaar per fiets. Voor de bioscoop zijn fietsenrekken aanwezig.', '1', 'N.B. Bovenstaande prijzen zijn per persoon, zijn niet geldig bij evenementen, speciale voorstellingen of besloten voorstellingen en altijd exclusief toeslagen en aanschaf 3D bril.\r\nVroege Vogel Voorstellingen gelden alleen (aanvang voor 12.00 uur) in het weekend en tijdens de schoolvakanties. De voorstelling is niet mogelijk in combinatie met andere kortingen en acties.\r\nVoor de bovengenoemde \"Speciale voorstellingen\" zijn kortingen en acties niet mogelijk.\r\nOp vertoon van een geldige CJP-Cultuurkaart, BankGiroLoterij VIP-kaart of studentenkaart aan de kassa van de bioscoop ontvang je korting. Let op: deze korting is alleen geldig van maandag t/m vrijdagmiddag maar niet gedurende vakanties (met uitzondering van de zomervakantie). Deze korting is per persoon en niet geldig in combinatie met andere kortingsacties, evenementen, speciale voorstellingen of besloten voorstellingen.\r\nFamilietickets zijn alleen geldig voor vier personen waarvan minimaal twee kinderen jonger dan 12 jaar en minimaal Ã©Ã©n volwassene. Alleen geldig bij kindervoorstellingen in de middag wanneer alle vier de personen naar dezelfde filmvoorstelling gaan. '),
('Kinepolis Den Bosch', 'denbosch.jpg', 'Bordeslaan 510', '5223 MX', 'Den Bosch', 'Noord-Brabant', '2018-10-16 12:00:00', '2018-10-16 16:00:00', 'Met de auto kunt u de bioscoop makkelijk bereiken. Let op: stel uw navigatie in op Spiegeltuin 1, Den Bosch. Hiermee komt u uit bij de Paleisgarage. In deze garage krijgt u tot 50% korting op het reguliere tarief tot maximaal 4 uur. U betaalt dan overdag tot 18.00 uur nog maar â‚¬ 1,15 per uur en na 18.00 uur nog maar â‚¬ 0.50 per uur. Aan de kassaâ€™s in de bioscoop kunt u deze korting verkrijgen. Na het parkeren neemt u de uitgang â€œBelvedereâ€ U zult ons vinden naast de Happy Italy. De parkeergarage is voorzien van parkeren voor minder validen en een lift. Er zijn tevens plaatsen om uw elektrische auto weer op te laden.', 'De bioscoop ligt op 5 minuten loopafstand van het centraal station. Met de bus kunt u ook in- en uitstappen bij de halte aan de onderwijsboulevard. Hier vindt u buslijnen: 8-9-121-135-136-203-207-239- 300-301-600-621-628-639-643. U kunt dus ook makkelijk vanaf de omliggende steden en dorpen met openbaar vervoer naar de bioscoop.', 'Voor de bioscoop is er plaats voor bijna 400 fietsen. Wij vragen u vriendelijk om uw fiets in de rekken te plaatsen zodat er genoeg loop- en fietsruimte is voor iedereen. Dank u voor uw medewerking. ', '1', 'N.B. Bovenstaande prijzen zijn per persoon, zijn niet geldig bij evenementen, speciale voorstellingen of besloten voorstellingen en altijd exclusief toeslagen.\r\nKinderen t/m 2 jaar hebben gratis toegang, wanneer ze bij een betalende volwassene op schoot zitten. Is dat niet wenselijk, dan dient er een ticket gekocht te worden.\r\nBij een kinderkaartje of jeugdkaartje kan naar het identiteitsbewijs van het kind/jongere gevraagd worden om de leeftijd vast te stellen. U dient deze dan te tonen om toegang te verkrijgen.\r\nOchtendvoorstellingen zijn enkel op weekenddagen, feestdagen en in vakanties tot 12:00 uur.\r\nOp vertoon van een geldige CJP/Cultuurkaart of studentenkaart aan de kassa van de bioscoop ontvang je korting. Let op: deze korting is alleen geldig van maandag t/m vrijdagmiddag maar niet gedurende vakanties (met uitzondering van de zomervakantie). Deze korting is per persoon en niet geldig in combinatie met andere kortingsacties, evenementen, speciale voorstellingen of besloten voorstellingen.\r\nVoor de voorwaarden van het familieticket, het 5-sterrenticket en de 10-sterrenticket zie de button hieronder.'),
('Kinepolis Den Helder', 'denhelder.jpg', 'Willemsoord 51', '1781 AS Den Helder', 'Den Helder', 'Noord-Holland', '2018-10-16 12:00:00', '2018-10-16 16:00:00', 'In Den Helder volgt u de ANWB borden richting Willemsoord, de bioscoop bevindt zich op dit terrein. De ingang van Willemsoord zit aan de route voor de veerboot naar Texel. Parkeren kan gratis op het Willemsoord terrein.', 'Kinepolis Den Helder is vanaf het trein- en busstation van CS Den Helder op 10-15 minuten loopafstand. Volg hiervoor de borden Willemsoord. ', 'Willemsoord is goed bereikbaar per fiets. Volg hiervoor de borden Willemsoord. Voor de bioscoop zijn fietsenrekken aanwezig.', '1', 'N.B. Bovenstaande prijzen zijn per persoon, zijn niet geldig bij evenementen, speciale voorstellingen of besloten voorstellingen en altijd exclusief toeslagen.\r\nKinderen t/m 2 jaar hebben gratis toegang, wanneer ze bij een betalende volwassene op schoot zitten. Is dat niet wenselijk, dan dient er een ticket gekocht te worden.\r\nBij een kinderkaartje kan naar het identiteitsbewijs van uw kind gevraagd worden om de leeftijd vast te stellen. U dient deze dan te tonen om toegang te verkrijgen.\r\nZondagochtend voordeel geldt alleen op zondag voor de voorstellingen tot 11:30 uur.\r\nOp vertoon van een geldige CJP/Cultuurkaart of BankGiro Loterij VIP-KAART aan de kassa van de bioscoop ontvang je korting. Let op: deze korting is alleen geldig van maandag t/m vrijdagmiddag maar niet gedurende vakanties (met uitzondering van de zomervakantie). Deze korting is per persoon en niet geldig in combinatie met andere kortingsacties, evenementen, speciale voorstellingen of besloten voorstellingen.\r\nVoor de voorwaarden van het familieticket, het 5-sterrenticket en de 10-sterrenticket zie FAQ.'),
('Kinepolis Dordrecht', 'dordrecht.jpg', 'Lijnbaan 200', '3311 RL ', 'Dordrecht', 'Zuid-Holland', '2018-10-16 12:00:00', '2018-10-16 15:00:00', 'Met de auto kunt u ons bereiken via de Noordendijk. U volgt de borden voor parkeergarage Energiehuis De parkeergarage staat naast de bioscoop. Parkeren in Garage Energiehuis: â‚¬3,- voor 4 uur. Afwaarderen aan onze kassas.', 'U kunt Kinepolis Dordrecht bereiken met buslijn 10, halte Energiehuis. Voor actuele bustijden kijkt u op www.arriva.nl', 'De parkeergarage heeft ook een zeer grote fietsenstalling.', '1', 'N.B. Bovenstaande prijzen zijn per persoon, zijn niet geldig bij evenementen, speciale voorstellingen of besloten voorstellingen en altijd exclusief toeslagen.\r\nKinderen t/m 2 jaar hebben gratis toegang, wanneer ze bij een betalende volwassene op schoot zitten. Is dat niet wenselijk, dan dient er een ticket gekocht te worden.\r\nBij een kinderkaartje kan naar het identiteitsbewijs van uw kind gevraagd worden om de leeftijd vast te stellen. U dient deze dan te tonen om toegang te verkrijgen.\r\nOchtendvoorstellingen zijn enkel op weekenddagen, feestdagen en in vakanties tot 12:00 uur.\r\nOp vertoon van een geldige CJP/Cultuurkaart, BankGiro Loterij VIP-KAART of studentenkaart aan de kassa van de bioscoop ontvang je korting. Let op: deze korting is alleen geldig van maandag t/m vrijdagmiddag maar niet gedurende vakanties (met uitzondering van de zomervakantie). Deze korting is per persoon en niet geldig in combinatie met andere kortingsacties, evenementen, speciale voorstellingen of besloten voorstellingen.\r\nVoor de voorwaarden van het familieticket, het 5-sterrenticket en de 10-sterrenticket zie FAQ.'),
('Kinepolis Emmen', 'emmen.jpg', 'Westeind 70', '7811 ME ', 'Emmen', 'Drenthe', '2018-10-16 12:00:00', '2018-10-16 18:00:00', 'De bioscoop is makkelijk te bereiken met de auto via de afrit van de N381. Volg de borden P Wildlands of Centrum Noor\'. Voor de bioscoop is er parkeergelegenheid voor € 1,70 per 58 minuten. Na 18:00u en op donderdag na 21:00 is parkeren gratis.', 'Kinepolis Emmen is per trein en bus bereikbaar. Vanaf station Emmen is de bioscoop op 10 minuten loopfastand. Met de bus is de bioscoop zeer makkelijk bereiken via halte Centrum Emmen of Frieslandweg. Vanaf hier loopt u in enkele minuten naar de bioscoop.', 'De bioscoop is per fiets bereikbaar. De fietsenstalling staat tegenover de bioscoop.', '1', 'N.B. Bovenstaande prijzen zijn per persoon, zijn niet geldig bij evenementen, speciale voorstellingen of besloten voorstellingen en altijd exclusief toeslagen.\r\nKinderen t/m 2 jaar hebben gratis toegang, wanneer ze bij een betalende volwassene op schoot zitten. Is dat niet wenselijk, dan dient er een ticket gekocht te worden.\r\nBij een kinderkaartje kan naar het identiteitsbewijs van uw kind gevraagd worden om de leeftijd vast te stellen. U dient deze dan te tonen om toegang te verkrijgen.\r\nZondagochtend voordeel geldt alleen op zondag voor de voorstellingen tot 11:30 uur.\r\nOp vertoon van een geldige CJP/Cultuurkaart of BankGiro Loterij VIP-KAART aan de kassa van de bioscoop ontvang je korting. Let op: deze korting is alleen geldig van maandag t/m vrijdagmiddag maar niet gedurende vakanties (met uitzondering van de zomervakantie). Deze korting is per persoon en niet geldig in combinatie met andere kortingsacties, evenementen, speciale voorstellingen of besloten voorstellingen.\r\nVoor de voorwaarden van het familieticket, het 5-sterrenticket en de 10-sterrenticket zie FAQ.'),
('Kinepolis Enschede', 'enschede.jpg', 'Colosseum 60', '7521 PT ', 'Enschede', 'Overijssel', '2018-10-16 12:00:00', '2018-10-16 15:00:00', 'Met de auto neemt u bij Enschede afslag 26 richting Universiteit/Stadion. Rij met de weg mee links om de Grolsch Veste. U ziet aan de rechterhand Kinepolis Enschede. U kunt uw auto gratis parkeren op één van de parkeerterreinen. Houdt u rekening met extra reistijd op speeldata van FC Twente.', 'Met het openbaar vervoer kunt u met de trein naar station Enschede Kennispark (voorheen Drienerlo). Dit station is te bereiken door middel van de stoptrein vanuit Enschede, Hengelo, Zwolle, Deventer of Almelo. Kinepolis Enschede ligt op ongeveer 5 á 10 minuten lopen vanaf het station.', '-', '1', 'N.B. Bovenstaande prijzen zijn per persoon, zijn niet geldig bij evenementen, speciale voorstellingen of besloten voorstellingen en altijd exclusief toeslagen.\r\nKinderen t/m 2 jaar hebben gratis toegang, wanneer ze bij een betalende volwassene op schoot zitten. Is dat niet wenselijk, dan dient er een ticket gekocht te worden.\r\nBij een kinderkaartje kan naar het identiteitsbewijs van uw kind gevraagd worden om de leeftijd vast te stellen. U dient deze dan te tonen om toegang te verkrijgen.\r\nOchtendvoorstellingen zijn enkel op weekenddagen, feestdagen en in vakanties tot 12:00 uur.\r\nOp vertoon van een geldige CJP/Cultuurkaart, BankGiro Loterij VIP-KAART of studentenkaart aan de kassa van de bioscoop ontvang je korting. Let op: deze korting is alleen geldig van maandag t/m vrijdagmiddag maar niet gedurende vakanties (met uitzondering van de zomervakantie). Deze korting is per persoon en niet geldig in combinatie met andere kortingsacties, evenementen, speciale voorstellingen of besloten voorstellingen.\r\nVoor de voorwaarden van het familieticket, het 5-sterrenticket en de 10-sterrenticket zie FAQ.'),
('Kinepolis Groningen', 'groningen.jpg', 'Boumaboulevard 53', '9723 ZS ', 'Groningen', 'Groningen5', '2018-10-16 12:00:00', '2018-10-16 15:00:00', 'Met de auto neemt u, komende vanaf het Julianaplein, afslag Groningen zuid oost richting Hoogezand, daarna neemt u de afslag Euroborg / Europapark. U kunt parkeren in de parkeergarage (P1) of op P2 (tegenover de Jumbo). In de bioscoop zijn kortingskaarten voor de parkeergarage verkrijgbaar. Deze kosten €4,80 per stuk en zijn vier uur geldig. Houdt u rekening met extra reistijd op speeldata van FC Groningen. Er zijn beperkte plaatsen beschikbaar in de parkeergarage op wedstrijddagen.', 'Met het openbaar vervoer kunt u vanaf het centraal station van Groningen buslijn 2 of 12 (stadsbus) en lijn 148 (streekbus) richting het Europapark, halte Boumaboulevard nemen. Vanaf de halte is het ongeveer 1 minuut lopen naar de bioscoop. Treinstation Europapark is tevens op loopafstand. ', '-', '1', 'NB bovenstaande prijzen per persoon en zijn niet geldig bij evenementen, speciale voorstellingen of besloten voorstellingen en altijd exclusief toeslagen.\r\nKinderen t/m 2 jaar hebben gratis toegang, wanneer ze bij een betalende volwassene op schoot zitten. Is dat niet wenselijk, dan dient er een ticket gekocht te worden.\r\nBij een kinderkaartje kan naar het identiteitsbewijs van uw kind gevraagd worden om de leeftijd vast te stellen. U dient deze dan te tonen om toegang te verkrijgen. \r\nOchtendvoorstellingen zijn enkel op weekenddagen, feestdagen en in vakanties tot 12:00 uur.\r\nOp vertoon van een geldige CJP/Cultuurkaart, BankGiro Loterij VIP-KAART of studentenkaart aan de kassa van de bioscoop ontvang je korting. Let op: deze korting is alleen geldig van maandag t/m vrijdagmiddag maar niet gedurende vakanties (met uitzondering van de zomervakantie). Deze korting is per persoon en niet geldig in combinatie met andere kortingsacties, evenementen, speciale voorstellingen of besloten voorstellingen.\r\nVoor de voorwaarden van het familieticket, het 5-sterrenticket en de 10-sterrenticket zie FAQ.'),
('Kinepolis Jaarbeurs Utrecht', 'utrechtjaarbeurs.jpg', 'Jaarbeursboulevard 300', '3521 BC ', 'Utrecht', 'Utrecht', '2018-10-16 12:00:00', '2018-10-16 12:00:00', 'Met de auto bereikt u Kinepolis Jaarbeurs door op de Ring Utrecht de blauwe ANWB-borden met de aanduiding \'Jaarbeurs\' te volgen. Rondom de Jaarbeurs is volop parkeergelegenheid. Parkeren op het Jaarbeursterrein is per 1 mei gratis voor alle automobilisten die een kaartje voor de film hebben gekocht. P1 en P3 zijn het gunstigst gelegen t.o.v. de bioscoop. Houdt u rekening met extra drukte op de parkeerplaatsen tijdens de beurzen in de Jaarbeurs hallen.', 'Kinepolis Jaarbeurs ligt naast de Jaarbeurshallen tegenover het Centraal Station van Utrecht en is dus uitstekend te bereiken met trein, bus en tram. Volg vanaf het Centraal Station de borden ‘Jaarbeursplein’ en loop richting de Jaarbeurshallen. Binnen enkele minuten vindt u de bioscoop aan uw linkerhand.', '-', '1', 'N.B. Bovenstaande prijzen zijn per persoon, zijn niet geldig bij evenementen, speciale voorstellingen of besloten voorstellingen en altijd exclusief toeslagen.\r\nKinderen t/m 2 jaar hebben gratis toegang, wanneer ze bij een betalende volwassene op schoot zitten. Is dat niet wenselijk, dan dient er een ticket gekocht te worden.\r\nBij een kinderkaartje kan naar het identiteitsbewijs van uw kind gevraagd worden om de leeftijd vast te stellen. U dient deze dan te tonen om toegang te verkrijgen.\r\nOchtendvoorstellingen zijn enkel op weekenddagen, feestdagen en in vakanties tot 12:00 uur.\r\nOp vertoon van een geldige CJP/Cultuurkaart, BankGiro Loterij VIP-KAART of studentenkaart aan de kassa van de bioscoop ontvang je korting. Let op: deze korting is alleen geldig van maandag t/m vrijdagmiddag maar niet gedurende vakanties (met uitzondering van de zomervakantie). Deze korting is per persoon en niet geldig in combinatie met andere kortingsacties, evenementen, speciale voorstellingen of besloten voorstellingen.\r\nVoor de voorwaarden van het familieticket, het 5-sterrenticket en de 10-sterrenticket zie FAQ.'),
('Kinepolis Oss', 'oss.jpg', 'Lievekamplaan 4-6', '5341 GW', 'Oss', 'Noord-Brabant', '2018-10-16 12:00:00', '2018-10-16 15:00:00', 'Met de auto volgt u de borden Centrum, Theater de Lievekamp of Politiebureau. De bioscoop bevindt zich naast het politiebureau. U kunt parkeren achter de bioscoop op het parkeerterrein voor € 4,00 per dag of € 1,45 per uur. Parkeren is ook mogelijk tegenover de bioscoop op de Lievekamplaan voor € 2,50 per uur.', 'Kinepolis Oss is bereikbaar vanaf het Centraal Station Oss op 10 minuten loopafstand. De bioscoop bevindt zich naast het politiebureau.', 'De bioscoop is per fiets bereikbaar en er is een (niet bewaakte) fietsenstalling aanwezig aan de voorzijde van de bioscoop.', '1', 'N.B. Bovenstaande prijzen zijn per persoon, zijn niet geldig bij evenementen, speciale voorstellingen of besloten voorstellingen en altijd exclusief toeslagen.\r\nKinderen t/m 2 jaar hebben gratis toegang, wanneer ze bij een betalende volwassene op schoot zitten. Is dat niet wenselijk, dan dient er een ticket gekocht te worden.\r\nBij een kinderkaartje kan naar het identiteitsbewijs van uw kind gevraagd worden om de leeftijd vast te stellen. U dient deze dan te tonen om toegang te verkrijgen.\r\nZondagochtend voordeel geldt alleen op zondag voor de voorstellingen tot 11:30 uur.\r\nOp vertoon van een geldige CJP/Cultuurkaart of BankGiro Loterij VIP-KAART aan de kassa van de bioscoop ontvang je korting. Let op: deze korting is alleen geldig van maandag t/m vrijdagmiddag maar niet gedurende vakanties (met uitzondering van de zomervakantie). Deze korting is per persoon en niet geldig in combinatie met andere kortingsacties, evenementen, speciale voorstellingen of besloten voorstellingen.\r\nVoor de voorwaarden van het familieticket, het 5-sterrenticket en de 10-sterrenticket zie FAQ.\r\nFAQ'),
('Kinepolis Zoetermeer', 'zoetermeer.jpg', 'Oostwaarts 70', '2711 BB ', 'Zoetermeer', 'Zuid-Holland', '2018-10-16 12:00:00', '2018-10-16 15:00:00', 'De bioscoop ligt in het centrum en is goed bereikbaar met de auto. Parkeren kan de eerste 2 uur gratis in de parkeergarage aan de Duitslandlaan (P9). Na sluitingstijd van de winkels zijn de buiten parkeerplaatsen gratis parkeren (ma-do en za-zo vanaf 18.00 uur en vr vanaf 21.00 uur).', 'U kunt ons met de bus zeer makkelijk bereiken via halte Oostwaarts (buslijn 71 en 72), Zwaardslootseweg (buslijn 70), Woonhart (buslijn 400) en Stadhuis (Randstadsrail). Voor actuele tijden van het openbaar vervoer kijkt u op 9292.nl. ', 'Bij de bushalte Oostwaarts en aan de Duitslandlaan achter de bioscoop zijn fietsenstallingen.', '1', 'N.B. Bovenstaande prijzen zijn per persoon, zijn niet geldig bij evenementen, speciale voorstellingen of besloten voorstellingen en altijd exclusief toeslagen.\r\nKinderen t/m 2 jaar hebben gratis toegang, wanneer ze bij een betalende volwassene op schoot zitten. Is dat niet wenselijk, dan dient er een ticket gekocht te worden.\r\nBij een kinderkaartje kan naar het identiteitsbewijs van uw kind gevraagd worden om de leeftijd vast te stellen. U dient deze dan te tonen om toegang te verkrijgen.\r\nZondagochtend voordeel geldt alleen op zondag voor de voorstellingen tot 12:00 uur.\r\nOp vertoon van een studentenkaart aan de kassa van de bioscoop ontvang je korting. Let op: deze korting is alleen geldig van maandag t/m vrijdagmiddag maar niet gedurende vakanties (met uitzondering van de zomervakantie). Deze korting is per persoon en niet geldig in combinatie met andere kortingsacties, evenementen, speciale voorstellingen of besloten voorstellingen.\r\nOp vertoon van een geldige CJP/Cultuurkaart aan de kassa van de bioscoop ontvang je korting. Let op: deze korting is alleen geldig van maandag t/m vrijdagmiddag maar niet gedurende vakanties (met uitzondering van de zomervakantie). Deze korting is per persoon en niet geldig in combinatie met andere kortingsacties, evenementen, speciale voorstellingen of besloten voorstellingen.\r\nOp vertoon van een geldige BankGiro Loterij VIP-KAART aan de kassa van de bioscoop ontvang je € 1,50 korting. Per bezoek kunt u 4 kaarten met korting bestellen per VIP-KAART. Voor o.a. extra lange vertoningen of 3D-films betaalt u een extra toeslag. De korting is alleen van maandag tot en met vrijdag geldig, niet in combinatie met andere kortingsacties, evenementen, speciale voorstellingen of besloten voorstellingen en niet geldig tijdens vakanties.\r\nVoor de voorwaarden van het familieticket, het 5-sterrenticket en de 10-sterrenticket zie FAQ.')
--
-- Indexen voor geëxporteerde tabellen
--

--
-- Indexen voor tabel `bioscopen`
--
ALTER TABLE `bioscopen`
  ADD PRIMARY KEY (`bios_id`);

--
-- AUTO_INCREMENT voor geëxporteerde tabellen
--

--
-- AUTO_INCREMENT voor een tabel `bioscopen`
--
ALTER TABLE `bioscopen`
  MODIFY `bios_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
